const weapons=[
{name:'Power Tool',type:'melee',desc:'A powered melee tool built for close-range smashing. A straightforward starting point for aggressive builds.',tags:['Melee','Impact','Powered']},
{name:'Junk Dog',type:'melee',desc:'Heavy close-range weaponry for getting right into the pit and turning momentum into damage.',tags:['Melee','Heavy','Impact']},
{name:'Nailgun',type:'nailgun',desc:'Ranged nail weapon. Useful when you want pressure without committing both arms to point-blank combat.',tags:['Ranged','Nails','Ammo']},
{name:'Nailgun II',type:'nailgun',desc:'Upgraded nailgun variant for ranged-focused builds.',tags:['Ranged','Nails','Upgrade']},
{name:'Grabber',type:'grab',desc:'Control-focused equipment for grabbing and manipulating enemies or objects during a fight.',tags:['Control','Grab','Utility']},
{name:'Blast Tool',type:'blast',desc:'Explosive/force-oriented option for builds that value burst and space control.',tags:['Blast','Burst','Control']}
];
const grid=document.querySelector('#grid'),search=document.querySelector('#search'),count=document.querySelector('#count');let filter='all',build={left:null,right:null};
function render(){const q=search.value.trim().toLowerCase();const list=weapons.filter(w=>(filter==='all'||w.type===filter)&&[w.name,w.desc,...w.tags].join(' ').toLowerCase().includes(q));count.textContent=`${list.length} shown`;grid.innerHTML=list.map(w=>`<article class="card"><span class="type">${w.type}</span><h3>${w.name}</h3><p>${w.desc}</p><div class="stats">${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="add" data-name="${w.name}">+ BUILD</button><a class="wiki" href="https://underdogs-vr.fandom.com/wiki/Special:Search?query=${encodeURIComponent(w.name)}" target="_blank" rel="noreferrer">Check community wiki ↗</a></article>`).join('')||'<p>No weapons match that search.</p>';document.querySelectorAll('.add').forEach(b=>b.onclick=()=>addToBuild(b.dataset.name))}
function addToBuild(name){const slot=!build.left?'left':!build.right?'right':'left';build[slot]=name;paintBuild()}
function paintBuild(){for(const side of ['left','right']){const el=document.querySelector(`#${side}Slot`);el.classList.toggle('filled',!!build[side]);el.innerHTML=`<small>${side.toUpperCase()}</small><strong>${build[side]||'Choose weapon'}</strong>`}}
document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelector('#filters .active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});search.addEventListener('input',render);document.querySelector('#clearBuild').onclick=()=>{build={left:null,right:null};paintBuild()};document.querySelectorAll('.slot').forEach(s=>s.onclick=()=>{build[s.dataset.slot]=null;paintBuild()});render();