const weapons=[
{name:'Knuckle Ball',type:'physical',phys:13,stun:13,rarity:'Common',action:'PUNCHES',ability:'13 Physical DMG.',img:'https://wisfins.com/wp-content/uploads/2025/01/Knuckle.jpg',tags:['Physical','Punch']},
{name:'Bomba',type:'physical',phys:18,stun:18,rarity:'Uncommon',action:'PUNCHES',ability:'18 Physical DMG.',img:'https://wisfins.com/wp-content/uploads/2025/01/Bomba.jpg',tags:['Physical','Punch']},
{name:'Buzz Saw',type:'overheat',phys:5,stun:null,rarity:'Uncommon',action:'SAWS',ability:'50 Physical DPS. Hold trigger and push into enemies to saw. Up to +30% Physical DPS when sawing deeper. Overheats after 3 sec of sawing. Punches deal 5 Physical DMG. -50% PWR.',img:'https://wisfins.com/wp-content/uploads/2025/01/saw.jpg',tags:['Physical','DPS','Overheat','Power']},
{name:'Fingers',type:'grab',phys:10,stun:10,rarity:'Uncommon',action:'GRABS',ability:'Grab by pressing the trigger button. Punches deal 10 Physical DMG.',img:'https://wisfins.com/wp-content/uploads/2025/01/Fingers.jpg',tags:['Physical','Grab','Control']},
{name:'Focused Blaster',type:'blast',phys:12,stun:null,rarity:'Rare',action:'BLAST',ability:'Slam the ground to emit a direct ranged blastwave that deals 0 DMG and pushes enemies away. Punches deal 12 Physical DMG. -50% PWR.',img:'https://wisfins.com/wp-content/uploads/2025/01/FocusedBlaster.jpg',tags:['Physical','Blastwave','Push','Power']},
{name:'Grappling Clamp',type:'grab',phys:8,stun:8,rarity:'Uncommon',action:'GRABS',ability:'Press trigger to shoot out, catch the target and pull it back. Punches deal 8 Physical DMG.',img:'https://wisfins.com/wp-content/uploads/2025/01/GrappleClamp.jpg',tags:['Physical','Grab','Pull','Control']},
{name:'Iron Nailgun',type:'nailgun',phys:16,stun:null,rarity:'Unknown',action:'NAILS',ability:'Hammers iron nails into enemies that stay 5 sec, with up to 5 active nails. Punches deal 16 Physical DMG. -50% PWR.',img:'https://wisfins.com/wp-content/uploads/2025/01/IronNailgun.jpg',tags:['Physical','Nails','Power']},
{name:'Blast Nailgun',type:'nailgun',phys:14,stun:null,rarity:'Uncommon',action:'BLAST NAILS',ability:'Hammers blast nails that emit radial blastwaves every 2 sec, with 1 active nail at a time. Punches deal 14 Physical DMG. -50% PWR.',img:'https://wisfins.com/wp-content/uploads/2025/01/Blast-Nailgun.jpg',tags:['Physical','Nails','Blastwave','Power']},
{name:'Wrecking Ball',type:'physical',phys:16,stun:null,rarity:'Unknown',action:'IMPACT',ability:'More in-game data coming from the next screenshot batch.',tags:['Physical']},
{name:'Slim Axe',type:'physical',phys:20,stun:20,rarity:'Unknown',action:'SLASH',ability:'More in-game data coming from the next screenshot batch.',tags:['Physical','Blade']},
{name:'Rocket Nailgun',type:'nailgun',phys:12,stun:12,rarity:'Unknown',action:'NAILS',ability:'More in-game data coming from the next screenshot batch.',tags:['Physical','Nails']},
{name:'Radial Blaster',type:'blast',phys:18,stun:null,rarity:'Unknown',action:'BLAST',ability:'More in-game data coming from the next screenshot batch.',tags:['Physical','Blastwave']}
];
const grid=document.querySelector('#grid'),search=document.querySelector('#search'),count=document.querySelector('#count'),detail=document.querySelector('#detail');let filter='all',build={leftWeapon:null,rightWeapon:null,leftArm:null,rightArm:null,bash:null};
function render(){const q=search.value.trim().toLowerCase();const list=weapons.filter(w=>(filter==='all'||w.type===filter)&&[w.name,w.action,w.ability,...w.tags].join(' ').toLowerCase().includes(q));count.textContent=`${list.length} / ${weapons.length}`;grid.innerHTML=list.map(w=>`<button class="weapon-tile" data-name="${w.name}"><div class="weapon-art">${w.img?`<img src="${w.img}" alt="${w.name}" loading="lazy">`:`<span>${w.name.split(' ').map(x=>x[0]).join('')}</span>`}</div><strong>${w.name}</strong><small>${w.action}</small></button>`).join('')||'<p>No weapons match that search.</p>';document.querySelectorAll('.weapon-tile').forEach(b=>b.onclick=()=>openDetail(b.dataset.name))}
function openDetail(name){const w=weapons.find(x=>x.name===name);detail.classList.add('open');detail.innerHTML=`<button class="close" aria-label="Close">×</button>${w.img?`<img class="detail-art" src="${w.img}" alt="${w.name}">`:''}<div class="detail-kicker">${w.type.toUpperCase()} • ${w.rarity.toUpperCase()}</div><h2>${w.name}</h2><h3>${w.action}</h3><div class="bigstats"><span><b>${w.phys??'?'}</b> PHYSICAL DMG</span>${w.stun!=null?`<span><b>${w.stun}</b> STUN DMG</span>`:''}</div><p>${w.ability}</p><div class="tagrow">${w.tags.map(t=>`<i>${t}</i>`).join('')}</div><div class="addrow"><button class="add" data-side="left">EQUIP LEFT</button><button class="add" data-side="right">EQUIP RIGHT</button></div>`;detail.querySelector('.close').onclick=()=>detail.classList.remove('open');detail.querySelectorAll('.add').forEach(b=>b.onclick=()=>equipWeapon(w.name,b.dataset.side))}
function equipWeapon(name,side){build[side+'Weapon']=name;paintBuild();detail.classList.remove('open')}
function paintBuild(){for(const side of ['left','right']){const el=document.querySelector(`#${side}Weapon`);const val=build[side+'Weapon'];el.classList.toggle('filled',!!val);el.querySelector('strong').textContent=val||'EMPTY'}document.querySelector('#leftArm strong').textContent=build.leftArm||'ARM TBD';document.querySelector('#rightArm strong').textContent=build.rightArm||'ARM TBD';document.querySelector('#bashSlot strong').textContent=build.bash||'BASH GUARD TBD'}
document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelector('#filters .active')?.classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});search.addEventListener('input',render);document.querySelector('#clearBuild').onclick=()=>{build={leftWeapon:null,rightWeapon:null,leftArm:null,rightArm:null,bash:null};paintBuild()};document.querySelectorAll('.equip-slot').forEach(s=>s.onclick=()=>{const key=s.dataset.key;if(key&&build[key]){build[key]=null;paintBuild()}});render();paintBuild();